run:
  deadline: 1m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs:
    - pkg/client
  modules-download-mode: readonly

linters:
  enable-all: true
  disable-all: false
  disable:
    - wsl
    - wrapcheck
    - goerr113
    - gomnd
    - exhaustruct
    - nestif
    - gofumpt
    - gochecknoinits
    - funlen
    - cyclop
    - goimports
    - gci
    - lll
    - gocognit
    - ifshort # deprecated
    - maligned # deprecated
    - golint # deprecated
    - interfacer  #deprecated
    - scopelint # deprecated
    - exhaustivestruct # deprecated

linters-settings:
  gosimple:
    checks:
      - all
      - '-S1024' # disable the rule S1024
