run:
  deadline: 1m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs:
    - pkg/client
  modules-download-mode: readonly

linters:
  enable:
    - vet
    - gofmt
    - deadcode
    - varcheck
    - structcheck
    - ineffassign
    - unconvert
    - misspell
  disable-all: false