name: pipeline

on:
  push:
    branches:
      - 'main'
      - 'release/**'

env:
  registry_url: "registry.hub.docker.com"
  image_repo: "kvendingoldo/aws-letsencrypt-lambda"

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.set_version.outputs.safe_version }}
    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry_url }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.10
        with:
          primary_branch: 'main'
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.registry_url }}/${{ env.image_repo }}:latest
            ${{ env.registry_url }}/${{ env.image_repo }}:${{ steps.set_version.outputs.safe_version }}
      -
        name: Print image version
        run: echo ${{ steps.set_version.outputs.safe_version }}
